# Generated by Django 5.2.6 on 2025-09-18 13:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["order_date_time", "order_number"],
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
            },
        ),
        migrations.RenameField(
            model_name="order",
            old_name="Product",
            new_name="product",
        ),
        migrations.RemoveField(
            model_name="order",
            name="order_date",
        ),
        migrations.AddField(
            model_name="order",
            name="order_date_time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
