# Generated by Django 5.2.6 on 2025-09-24 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0003_remove_cart_products_cartitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="product",
        ),
    ]
