# Generated by Django 5.2.6 on 2025-09-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0005_order_address_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Создан"),
                    ("padding", "Отправлен"),
                    ("delivered", "Доставлен"),
                    ("cancelled", "Отменен"),
                ],
                default="created",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_method",
            field=models.CharField(
                choices=[
                    ("self_pickup", "Самовывоз"),
                    ("pick_up_point", "В пункт выдачи"),
                    ("mail", "Почтой"),
                    ("courier", "Курьером"),
                ],
                default="self_pickup",
                max_length=100,
            ),
        ),
    ]
