# Generated by Django 5.2.6 on 2025-09-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0006_order_status_alter_order_delivery_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_date_time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
