# Generated by Django 5.2.6 on 2025-09-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0007_alter_order_order_date_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Manager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=100, unique=True)),
                ("is_staff", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Менеджер",
                "verbose_name_plural": "Менеджеры",
                "ordering": ["first_name", "last_name"],
            },
        ),
        migrations.AlterField(
            model_name="order",
            name="order_date_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
