# Generated by Django 5.2.6 on 2025-09-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0008_manager_alter_order_order_date_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="manager",
            name="telegram_id",
            field=models.CharField(default=0, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
