# Generated by Django 5.2.6 on 2025-09-26 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0009_manager_telegram_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Manager",
        ),
    ]
